export {
  APPLICATION_PUSH_MAX_ATTEMPTS,
  applyPulledMappings,
  defaultDeviceName,
  deleteApplication,
  flattenMappingStore,
  foldMappingRows,
  forgetAllApplicationSyncRecords,
  forgetApplicationSyncRecords,
  hasVaultKey,
  isApplicationPushBlocked,
  isPaired,
  isVersionConflict,
  listAllApplications,
  listApplications,
  listBlockedApplications,
  noteApplicationPushed,
  noteApplicationRefused,
  patchApplication,
  pullMappings,
  pullProfileBlob,
  pushApplication,
  pushApplications,
  pushMappings,
  pushProfileBlob,
  readApplicationSyncMap,
  readLocalMappings,
  readSyncState,
  readVaultKey,
  remoteClientIdFor,
  requestPairing,
  status,
  SYNC_ROUTES,
  toBusError,
  unpair,
  wireClientIdFor,
  writeVaultKey,
} from '@/sync/client';

export type {
  ApplicationPage,
  ApplicationSyncMap,
  ApplicationSyncRecord,
  BlockedApplication,
  PushApplicationsResult,
  PushedApplication,
  SyncError,
  SyncErrorCode,
  SyncResult,
  VersionConflictError,
} from '@/sync/client';

export {
  base64ToBytes,
  buildSyncProfileVault,
  bytesToBase64,
  canOpenProfileVault,
  DEVICE_TOKEN_MAGIC,
  E2E_MAGIC,
  forgetInstallSecret,
  generateVaultKey,
  hasSealedHeader,
  isBase64OfLength,
  isVaultError,
  isVaultKey,
  openBlob,
  openDeviceToken,
  openProfileVault,
  openVaultKey,
  passphraseMaterial,
  randomBytes,
  rawKeyMaterial,
  sealBlob,
  sealDeviceToken,
  sealProfileVault,
  sealVaultKey,
  syncProfileVaultSchema,
  VaultError,
} from '@/sync/e2e';

export type { SealedBlob, SealedBlobMagic, SyncProfileVault, VaultKeyMaterial } from '@/sync/e2e';

export {
  assertSyncSafe,
  checkSyncSafe,
  classifySyncBody,
  GEMINI_KEY_PATTERN,
  isKeyShaped,
  isSyncGuardError,
  SYNC_BODY_KINDS,
  SyncGuardError,
} from '@/sync/guard';

export type { SyncBodyKind, SyncGuardReason } from '@/sync/guard';
