/**
 * tests/unit/signature.test.ts — JF-001 Rev 3.0 SEC 11 (Unit · "signature builder").
 *
 * `core/signature.ts` has exactly two jobs and both of them are load-bearing:
 *
 *   LABEL RESOLUTION (SEC 6.2). Everything the matcher does downstream is built on `sig.label`.
 *   The priority order is `<label for>` → wrapping `<label>` → `aria-labelledby` → `aria-label` →
 *   preceding text → table cell / `<dt>`, and a *lower* strategy must never win when a higher one
 *   has an answer.
 *
 *   HASH STABILITY (SEC 7.3). `sig.hash` is the key of `jf.mappings[domain]`. If the digest for
 *   the same field changes between page loads, every correction the user ever made (F-13) silently
 *   stops applying. That is why `frameId` is excluded and why generated ids are stripped of their
 *   volatile digits — and it is why those two properties are asserted here rather than assumed.
 */

import { describe, expect, it } from 'vitest';

import {
  SIGNATURE_FINGERPRINT_VERSION,
  buildFieldSignature,
  inferInputType,
  isComboboxPattern,
  looksAutoGenerated,
  normalizeIdentifier,
  resolveLabel,
  resolveSectionHeading,
  signatureFingerprint,
  signatureHash,
} from '@/core/signature';
import type { HashableSignature } from '@/core/signature';

import { unloadFixture } from '../setup';

/** Render a fragment into the live document and return the control under test. */
function mount(html: string, selector = 'input,select,textarea,[role],[contenteditable]'): Element {
  unloadFixture();
  document.body.innerHTML = html;
  const el = document.querySelector(selector);
  if (el === null) throw new Error(`mount(): nothing matched ${selector}`);
  return el;
}

/* ------------------------------------------------------------------------------------------------
 * SEC 6.2 — label resolution, in priority order
 * ---------------------------------------------------------------------------------------------- */

describe('resolveLabel — the SEC 6.2 strategy chain', () => {
  it('1 · <label for=id> wins, with the required asterisk de-noised away', () => {
    const el = mount(`
      <label for="fn">First Name <span class="req">*</span></label>
      <input id="fn" name="first_name" aria-label="ignored aria label" />
    `);
    expect(resolveLabel(el)).toEqual({ text: 'First Name', source: 'label-for' });
  });

  it('2 · a wrapping <label> is used when there is no explicit for=', () => {
    const el = mount(`
      <label class="application-label">
        <div class="application-label-inner">Full name</div>
        <input name="name" />
      </label>
    `);
    expect(resolveLabel(el)).toEqual({ text: 'Full name', source: 'label-wrapping' });
  });

  it('3 · aria-labelledby, joining every referenced id in order', () => {
    const el = mount(`
      <span id="q-title">Why do you want to work here</span>
      <span id="q-hint">Maximum 500 words</span>
      <textarea aria-labelledby="q-title q-hint" name="ce4f1a02"></textarea>
    `);
    const resolved = resolveLabel(el);
    expect(resolved.source).toBe('aria-labelledby');
    expect(resolved.text).toContain('Why do you want to work here');
    expect(resolved.text).toContain('Maximum 500 words');
  });

  it('4 · aria-label, when nothing structural labels the field', () => {
    const el = mount(`<input name="q" aria-label="Portfolio URL" />`);
    expect(resolveLabel(el)).toEqual({ text: 'Portfolio URL', source: 'aria-label' });
  });

  it('5 · preceding sibling text — the div-soup case most custom ATS widgets land in', () => {
    const el = mount(`
      <div class="field">
        <div class="field-title">Postal Code</div>
        <input name="postal" />
      </div>
    `);
    expect(resolveLabel(el)).toEqual({ text: 'Postal Code', source: 'preceding-text' });
  });

  it('a flat table layout is already covered by strategy 5, and resolves to the same text', () => {
    // Strategy 5 is greedy: the `<td>` holding the caption is a previous sibling of the `<td>`
    // holding the control, so `preceding-text` answers before the table-cell branch is consulted.
    // The TEXT is what the matcher scores, and it is identical either way.
    const el = mount(`
      <table>
        <tr>
          <td>Home Phone</td>
          <td><input name="homePhone" /></td>
        </tr>
      </table>
    `);
    expect(resolveLabel(el)).toEqual({ text: 'Home Phone', source: 'preceding-text' });
  });

  it('6a · the table cell to the left, once the control is nested out of strategy 5’s reach', () => {
    // `precedingText` climbs at most LABEL_ANCESTOR_DEPTH (4) ancestors. Legacy iCIMS/Taleo
    // markup wraps controls in several presentational divs, which is exactly when the table-cell
    // fallback earns its keep.
    const el = mount(`
      <table>
        <tr>
          <td>Home Phone</td>
          <td><div><div><div><div><input name="homePhone" /></div></div></div></div></td>
        </tr>
      </table>
    `);
    expect(resolveLabel(el)).toEqual({ text: 'Home Phone', source: 'table-cell' });
  });

  it('6b · the <dt> of a definition list, likewise', () => {
    const el = mount(`
      <dl>
        <dt>Current Employer</dt>
        <dd><div><div><div><div><input name="org" /></div></div></div></div></dd>
      </dl>
    `);
    expect(resolveLabel(el)).toEqual({ text: 'Current Employer', source: 'definition-list' });
  });

  it('falls back to title=, then to the empty string — it never invents text (INV-4)', () => {
    expect(resolveLabel(mount(`<input name="x" title="Expected salary" />`))).toEqual({
      text: 'Expected salary',
      source: 'title-attr',
    });
    expect(resolveLabel(mount(`<div><input name="x" /></div>`))).toEqual({
      text: '',
      source: 'none',
    });
  });

  it('a higher strategy always beats a lower one', () => {
    const el = mount(`
      <span id="aria-source">From aria-labelledby</span>
      <label for="target">From label-for</label>
      <div>From preceding text</div>
      <input id="target" name="n" aria-labelledby="aria-source" aria-label="From aria-label" title="From title" />
    `);
    expect(resolveLabel(el).source).toBe('label-for');
    expect(resolveLabel(el).text).toBe('From label-for');
  });
});

/* ------------------------------------------------------------------------------------------------
 * SEC 6.3 — the section heading that drives the −20 modifier
 * ---------------------------------------------------------------------------------------------- */

describe('resolveSectionHeading', () => {
  it('reads the nearest preceding h1–h4', () => {
    const el = mount(`
      <h3>References</h3>
      <div class="field"><label for="rn">Name</label><input id="rn" name="reference_name" /></div>
    `);
    expect(resolveSectionHeading(el)).toBe('References');
  });

  it('prefers a fieldset legend over an outer heading', () => {
    const el = mount(`
      <h2>Application</h2>
      <fieldset>
        <legend>Emergency Contact</legend>
        <label for="ec">Name</label>
        <input id="ec" name="emergency_name" />
      </fieldset>
    `);
    expect(resolveSectionHeading(el)).toBe('Emergency Contact');
  });

  it('honours aria-labelledby on a role=group ancestor (Workday / Ashby question groups)', () => {
    const el = mount(`
      <span id="grp">Voluntary Self-Identification</span>
      <div role="group" aria-labelledby="grp">
        <label for="g">Gender</label>
        <select id="g" name="gender"><option>Female</option></select>
      </div>
    `);
    expect(resolveSectionHeading(el)).toBe('Voluntary Self-Identification');
  });

  it('returns "" when the field sits under no heading at all', () => {
    expect(resolveSectionHeading(mount(`<div><input name="loose" /></div>`))).toBe('');
  });
});

/* ------------------------------------------------------------------------------------------------
 * SEC 6.2 — input-type inference
 * ---------------------------------------------------------------------------------------------- */

describe('inferInputType', () => {
  const cases: ReadonlyArray<readonly [string, string]> = [
    ['<input name="a" />', 'text'],
    ['<input type="text" name="a" />', 'text'],
    ['<input type="search" name="a" />', 'text'],
    ['<input type="number" name="a" />', 'text'],
    ['<input type="email" name="a" />', 'email'],
    ['<input type="tel" name="a" />', 'tel'],
    ['<input type="url" name="a" />', 'url'],
    ['<input type="date" name="a" />', 'date'],
    ['<input type="month" name="a" />', 'date'],
    ['<input type="file" name="a" />', 'file'],
    ['<input type="checkbox" name="a" />', 'checkbox'],
    ['<input type="radio" name="a" />', 'radio'],
    ['<textarea name="a"></textarea>', 'textarea'],
    ['<select name="a"><option>x</option></select>', 'select'],
    // `role=textbox` without `aria-multiline` is a SINGLE-line box, whatever contenteditable says.
    ['<div role="textbox" contenteditable="true"></div>', 'text'],
    ['<div role="textbox" aria-multiline="true" contenteditable="true"></div>', 'textarea'],
    ['<div contenteditable="true"></div>', 'textarea'],
    ['<div role="checkbox" aria-checked="false"></div>', 'checkbox'],
    ['<div role="listbox"></div>', 'select'],
  ];

  for (const [html, expected] of cases) {
    it(`${html} → ${expected}`, () => {
      expect(inferInputType(mount(html))).toBe(expected);
    });
  }

  it('an ARIA typeahead is a combobox, not a text field (SEC 6.4 needs the distinction)', () => {
    const el = mount(`
      <input name="loc" role="combobox" aria-autocomplete="list" aria-controls="lb" />
      <ul id="lb" role="listbox"></ul>
    `);
    expect(isComboboxPattern(el)).toBe(true);
    expect(inferInputType(el)).toBe('combobox');
  });

  it('aria-controls pointing at a listbox is enough on its own (ARIA 1.1 shape)', () => {
    const el = mount(`
      <input name="loc" aria-controls="lb2" />
      <ul id="lb2" role="listbox"></ul>
    `);
    expect(inferInputType(el)).toBe('combobox');
  });

  it('Workday renders its selects as buttons — role decides, not the tag', () => {
    const el = mount(
      `<button type="button" role="combobox" data-automation-id="countryDropdown" aria-haspopup="listbox">Select One</button>`,
      'button',
    );
    expect(inferInputType(el)).toBe('combobox');
  });

  it('a native <datalist> input stays text — it is filled by writing, not by the typeahead dance', () => {
    const el = mount(`
      <input name="city" list="cities" />
      <datalist id="cities"><option value="Bengaluru"></option></datalist>
    `);
    expect(isComboboxPattern(el)).toBe(false);
    expect(inferInputType(el)).toBe('text');
  });
});

/* ------------------------------------------------------------------------------------------------
 * SEC 7.3 — hash stability
 * ---------------------------------------------------------------------------------------------- */

describe('signatureHash — the mapping key must survive a reload', () => {
  const base: HashableSignature = {
    label: 'First Name',
    name: 'first_name',
    id: 'first_name',
    placeholder: '',
    ariaLabel: '',
    autocomplete: '',
    inputType: 'text',
    sectionHeading: 'Personal Information',
    frameId: 0,
  };

  it('is a 40-character SHA-1 hex digest', () => {
    expect(signatureHash(base)).toMatch(/^[0-9a-f]{40}$/);
  });

  it('is deterministic — the same input always hashes the same', () => {
    expect(signatureHash(base)).toBe(signatureHash({ ...base }));
  });

  it('carries the fingerprint version so a format change cannot collide silently', () => {
    expect(signatureFingerprint(base).startsWith(`${SIGNATURE_FINGERPRINT_VERSION}|`)).toBe(true);
  });

  it('IGNORES frameId — Chrome renumbers frames on every navigation', () => {
    expect(signatureHash({ ...base, frameId: 7 })).toBe(signatureHash(base));
    expect(signatureFingerprint({ ...base, frameId: 7 })).toBe(signatureFingerprint(base));
  });

  it('ignores label casing, surrounding punctuation and the required asterisk', () => {
    expect(signatureHash({ ...base, label: 'first name' })).toBe(signatureHash(base));
    expect(signatureHash({ ...base, label: 'First Name *' })).toBe(signatureHash(base));
    expect(signatureHash({ ...base, label: '  First   Name  ' })).toBe(signatureHash(base));
  });

  it('strips volatile digits out of generated ids (React / MUI / Workday)', () => {
    expect(looksAutoGenerated(':r7:')).toBe(true);
    expect(looksAutoGenerated('mui-1421')).toBe(true);
    expect(looksAutoGenerated('input_3_1')).toBe(true);
    expect(looksAutoGenerated('first_name')).toBe(false);

    const render1: HashableSignature = { ...base, id: ':r7:', name: '' };
    const render2: HashableSignature = { ...base, id: ':r91:', name: '' };
    expect(signatureHash(render1)).toBe(signatureHash(render2));
  });

  it('keeps a MEANINGFUL trailing digit — address line 1 ≠ address line 2', () => {
    expect(looksAutoGenerated('address2')).toBe(false);
    expect(normalizeIdentifier('address1')).not.toBe(normalizeIdentifier('address2'));
    const line1: HashableSignature = { ...base, label: 'Address Line 1', id: 'address1', name: 'address1' };
    const line2: HashableSignature = { ...base, label: 'Address Line 2', id: 'address2', name: 'address2' };
    expect(signatureHash(line1)).not.toBe(signatureHash(line2));
  });

  it('changes when the field genuinely changes meaning', () => {
    expect(signatureHash({ ...base, label: 'Last Name' })).not.toBe(signatureHash(base));
    expect(signatureHash({ ...base, inputType: 'email' })).not.toBe(signatureHash(base));
    expect(signatureHash({ ...base, sectionHeading: 'References' })).not.toBe(signatureHash(base));
    expect(signatureHash({ ...base, autocomplete: 'given-name' })).not.toBe(signatureHash(base));
  });
});

describe('buildFieldSignature', () => {
  it('assembles the whole SEC 6.2 record from the DOM', () => {
    const el = mount(`
      <h3>Personal Information</h3>
      <label for="email">Email <span>*</span></label>
      <input
        type="email"
        id="email"
        name="job_application[email]"
        placeholder="you@example.com"
        autocomplete="EMAIL"
      />
    `);
    const sig = buildFieldSignature(el, 3);

    expect(sig.label).toBe('Email');
    expect(sig.name).toBe('job_application[email]');
    expect(sig.id).toBe('email');
    expect(sig.placeholder).toBe('you@example.com');
    expect(sig.autocomplete).toBe('email');
    expect(sig.inputType).toBe('email');
    expect(sig.sectionHeading).toBe('Personal Information');
    expect(sig.frameId).toBe(3);
    expect(sig.hash).toMatch(/^[0-9a-f]{40}$/);
  });

  it('accepts a bare frame id or an options object interchangeably', () => {
    const el = mount(`<label for="p">Phone</label><input id="p" name="phone" type="tel" />`);
    expect(buildFieldSignature(el, 0)).toEqual(buildFieldSignature(el, { frameId: 0 }));
  });

  it('groupLabel signs a radio group by its QUESTION, not by the option caption', () => {
    unloadFixture();
    document.body.innerHTML = `
      <fieldset>
        <legend>Are you legally authorized to work in the European Union?</legend>
        <label for="y">Yes</label><input type="radio" id="y" name="auth" value="Yes" />
        <label for="n">No</label><input type="radio" id="n" name="auth" value="No" />
      </fieldset>
    `;
    const yes = document.querySelector('#y');
    const no = document.querySelector('#n');
    expect(yes).not.toBeNull();
    expect(no).not.toBeNull();
    if (yes === null || no === null) return;

    const sigYes = buildFieldSignature(yes, { groupLabel: true, nameOverride: 'auth' });
    const sigNo = buildFieldSignature(no, { groupLabel: true, nameOverride: 'auth' });

    expect(sigYes.label).toBe('Are you legally authorized to work in the European Union?');
    // Both options are the same question: the group hashes to one stable key.
    expect(sigYes.hash).toBe(sigNo.hash);
    // …whereas the per-option label would have produced two different keys.
    expect(buildFieldSignature(yes).label).toBe('Yes');
    expect(buildFieldSignature(yes).hash).not.toBe(buildFieldSignature(no).hash);
  });

  it('labelOverride lets an adapter beat the DOM', () => {
    const el = mount(`<div><input name="q1" /></div>`);
    expect(buildFieldSignature(el, { labelOverride: 'Expected salary' }).label).toBe(
      'Expected salary',
    );
  });
});
